#!/bin/bash

## Each */txtar script deletes the records it creates.
## So this script only comes in handy if "go test" fails, 
## leaving records behind, and you want to start over.

ibapi authzone delete seci.rice.edu --assumeyes 
ibapi authzone delete seci.rice.edu --assumeyes -V external
ibapi authzone add seci.rice.edu
ibapi authzone add seci.rice.edu -V external

ibapi ptr delete ptr1.seci.rice.edu 10.10.10.221
ibapi ptr delete ptr1.seci.rice.edu 10.10.10.222
ibapi ptr delete ptr2.seci.rice.edu 10.10.10.221
ibapi ptr delete ptr2.seci.rice.edu 10.10.10.222
ibapi ptr delete ptr3.seci.rice.edu 10.10.10.222
ibapi ptr delete ptr-a.seci.rice.edu 10.10.10.231

